### ISSUE TITLE
macos amd64 不能完全退出、默认没有勾选系统代理、开启代理后要等20多秒才能使用

### ISSUE THREAD

**Issue by tudoubocai** [topoge/NgX#5]
首先，非常感谢作者能提供Mac版的客户！
没有完全退出的后台导致官方终端版的客户端不能运行。
刚下载设置好后，系统代理没有勾选，导致不能使用。
开启后等待较长时间才能用，不是线路或者服务器问题，官方版的秒开。

**Comment by ktver** [comment]
1. macOS退出问题，正在解决中
2. 默认不开启系统代理，只是建立了代理端口，需要程序自行连接
3. 默认开启了DNS所以导致了这个问题，目前正在解决中，后面会默认关闭DNS功能
